### ISSUE TITLE
Unsafe behaviour: Mail loads remote images by default

### ISSUE THREAD

**Issue by Melyanna** [elementary/mail#183]
It is possible to turn the automatic loading of remote images off, but not when setting up an account for the first time.
This means that after having set an email account, the app starts loading email - and remote images - before the user has a chance to turn the feature off.
A better behaviour would be to ask users what they want to do at account creation or have the feature switched off by default.

**Comment by danrabbit** [comment]
It looks like we made this setting the default around 2 years ago after GMail also made this the default: https://code.launchpad.net/~purejava/pantheon-mail/always-show-images/+merge/282523

I'm going to close this as a "Won't Fix" since most users probably want their full HTML emails to display properly and not loading images by default breaks a large quantity of email.

You'll notice that messages in the "Spam" folder are exempt from this setting (they always prompt you) and images are loaded on demand when you open an email (so mail you haven't opened won't have loaded images)

**Comment by baimafeima** [comment]
@danrabbit This issue was discussed [here](https://www.reddit.com/r/linux/comments/87mlpb/elementary_os_has_changed_my_view_on_linux/) and I think there were valid points about having the loading of remote images turned off. Please confirm whether this has been fixed as originally requested. I also see it as a problematic privacy violation which contradicts the main message on the eOS website that privacy is a major concern.

**Comment by 4jNsY6fCVqZv** [comment]
Blocking the loading of images by default would help to protect the security & privacy of Mail users. Which is becoming more and more difficult these days anyway. Is it possible to discuss the implications of this issue for Mail 2.0 again?

An alternative solution could of course be to make this functionality optionally available to users via the app settings.

**Comment by 4jNsY6fCVqZv** [comment]
Does this discussion status still apply to Mail 2.0? 

And if so, is it possible for you to empower users to block/suppress the loading of images and HTML in emails by default? E.g. by an additional switch in the App settings?

At least I know that from Evolution and consider it an important option of a modern email client that focuses on the protection of its users.
