### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by harisvsulaiman** [elementary/mail#229]
The mail app will look better with a dark mode with a toggle just like the one in lookbook app by @danrabbit.

thoughts, cc @cassidyjames .

**Comment by cassidyjames** [comment]
@harisvsulaiman please mention @elementary/ux for UX input, as there's more than just me on the UX team. :wink: 

That said, I'm not sure a dark mode makes sense. The primary content of an email client is, well, emails. The overwhelming standard for emails is to assume a white background and dark text for the content. If the contents of the mail are bright, then there doesn't seem to be a huge benefit to making the chrome of the app itself dark. And I definitely don't think we want to dive into the rabbit hole that is trying to override HTML email stylesheets inside the app.

**Comment by danrabbit** [comment]
I would add that the reason lookbook has a quick toggle for dark and light styles is because of its function of previewing icons in your app. LookBook doesn’t necessarily know what style your app looks like, so being able to preview both styles directly helps it fulfill its primary function. So it’s not a setting for the sake of a preference but a really purposeful feature that’s meant to be changed regularly
