### ISSUE TITLE
Starred emails folder doesn't show in sidebar

### ISSUE THREAD

**Issue by SamMakesCode** [elementary/mail#236]
Would be nice to be able to toggle on/off only starred messages. Seems like a fairly big feature that's missing (unless I'm missing something).

**Comment by danrabbit** [comment]
You can see your starred emails by clicking the "Starred" folder in the sidebar under any account

**Comment by samlittler** [comment]
In that case, there's a bug with the menu on the left as I don't have a starred folder.

**Comment by danrabbit** [comment]
Hm Reopening the issue, but I can't confirm

**Comment by samlittler** [comment]
Hi, yes. I hope this is sufficient evidence?

[https://ibb.co/dyOf2e](https://ibb.co/dyOf2e)

**Comment by cassidyjames** [comment]
@danrabbit is it possible this is some special Gmail handling thing?

**Comment by danrabbit** [comment]
@cassidyjames that's very possible. It might be that GMail creates a real folder for this and this isn't a virtual folder

**Comment by cassidyjames** [comment]
@samlittler that's what I'm getting at—it could be that Dan is seeing the starred folder because it's something that's only in Gmail or GSuide accounts, and you're _not_ seeing it because you're not using one. Historically the codebase has done some special handling with Gmail which is why it's relevant.

Ideally, yeah, we could filter down to just starred messages regardless of email provider. But Gmail might be providing "Starred" as yet another folder on the server, which made it easy for those account types.

**Comment by DanyGee** [comment]
I use 3 gmail accounts with pantheon mail and I also don't get starred folder in the pane.

**Comment by cassidyjames** [comment]
That's definitely strange. I've used a handful of Gmail and GSuite accounts and they all get the "Starred" folder. 

@DanyGee, @samlittler: How did you set up the email accounts originally: in Mail, or in System Settings?

**Comment by DanyGee** [comment]
> @DanyGee, @samlittler: How did you set up the email accounts originally: in Mail, or in System Settings?

I did it directly in mail, as usual.
I get starred folder in Mailspring for example.

**Comment by marbetschar** [comment]
+1 for the ability to filter for starred messages. Probably just an activatable icon in the search field would do.
