### ISSUE TITLE
Account Settings...

### ISSUE THREAD

**Issue by Ordissimo** [elementary/mail#307]
I am on Ubuntu 18.04.
I can not set up an account
To get to use the application I go through gnome-control-center.
Below is the error encountered when pressing the button.

** (io.elementary.mail:4049): WARNING **: 11:34:17.072: HeaderBar.vala:111: Failed to open account settings: The specified location is not supported

I was hoping for the same behavior as calendar.

**Comment by danrabbit** [comment]
This is because Mail uses `settings://` URLs and this is not yet supported by GNOME Control Center. As of now, this URL scheme is only supported in Pantheon.

Alternatively you can use Evolution to set up accounts since Mail pulls from the same mailing backend.

Closing as "Out of Scope" since Mail can't force GNOME Control Center to support the settings URL scheme

**Comment by mizzunet** [comment]
I'm on Artix using SwayWM. Is there any way to setup an account manually?

**Comment by cassidyjames** [comment]
@mizzunet you can install Evolution and use it to set up your account since Mail uses the same back-end.
