### ISSUE TITLE
Connect gmail account via oauth2 api

### ISSUE THREAD

**Issue by ruslankonev** [elementary/mail#41]

**Comment by cassidyjames** [comment]
Right now Mail uses its own custom back-end to communicate with servers, which is why it's IMAP-only. There is some very, very early work on porting to an Evolution Data Server back-end which would potentially allow POP3 support as well.

I can pretty safely say we're not going to significantly rework the existing back-end, so I'm considering this blocked by EDS for now.

**Comment by cassidyjames** [comment]
EDS filed as #15

**Comment by bksubhuti** [comment]
I think that thunderbird works without the need to have "less secure apps" checked.  I think this is a big show stopper for people to try Mail, which is one of the key differences in eOS compared to other OS's .  I sort of trust you guys, so I allowed it.  It is a nice app.  Only recently did I "discover" this.  For this reason, it should be a priority.  When you cannot connect to gmail, the regular user will think it is a useless buggy program.  power users know differently..

**Comment by ruslankonev** [comment]
I want to try eOS mail program, but I can't connect with gmail because I have a 2FA and google account password will not accepted a gmail server via IMAP (maybe it different) and that is problem.  I have only one way to connect to my gmail acc — if Mail program will connect via oAuth api, like a Spark email client on MacOS

**Comment by gugacavalieri** [comment]
Hey guys, is this really closed? 

I would love to help to get this functionality running :)

There is some doc in here: https://developers.google.com/gmail/api/auth/about-auth

**Comment by andbuitra** [comment]
Hello,

Of course OAuth would be the best way. However, I think using one time password from Google might be a workaround. I can't test this right now since my Pantheon Mail has completely crashed for the "window resizing" bug but I did try this on latest available (on default repos) Geary and worked without any issues.

Like I said, it's not ideal since the targeted audience for elementary OS is not a "power user" that can know that Google has this service and how to use it but still a workaround for those who need Gmail in their lives and can't stay away from the almost perfect ecosystem.

**Comment by cellsheet** [comment]
I would not consider google's SSO to be a "power user" as you cannot login to anything with google without entering your credentials through their oAuth form for linking accounts such as social media sign-on's on various accounts (i.e. Google+ Login button). Everyone is familiar with the interface and the process and in in turn, would know of the login form. It seems less "targeted" and moreso "advanced" to allow less secure apps to use your account as this sounds like a security vulnerability in the making since you must take these steps yourself (this may put off a bit of people including me) rather than typing in your user information through a secured login mechanism. I would recommend considering implementing this feature for users to ensure a secure transaction. Please let me know if I'm overlooking or missing anything on this.

**Comment by tintou** [comment]
@cellsheet you're misinterpreting the previous comment.
It's of course a future feature but we don't have any date to give right now.

**Comment by cellsheet** [comment]
My apologies. Indeed I interpreted the previous statement as reasoning against oauth for some reason. Looking forward to this feature.

**Comment by MacOSO** [comment]
To enter, you can use the [Google application passwords](https://myaccount.google.com/apppasswords)

**Comment by blackst0ne** [comment]
Any ETA?

**Comment by sgmiller** [comment]
Google application passwords is not an option for those of us in companies who have disabled that feature for security reasons.  Would *really* like this to work.

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Comment by blackst0ne** [comment]
@danrabbit is it possible to try the new version of Mail?

**Comment by cassidyjames** [comment]
@blackst0ne it's in the master branch here, but you'd have to set up EDS yourself and compile Mail. So no, not easily.

**Comment by lsmith77** [comment]
just installed juno 5.0 and mail still does not seem to support oauth for gmail. so is this on the radar?

**Comment by lsmith77** [comment]
or what is the ETA for the “complete rewrite”? is there already something that can be tested?

**Comment by cassidyjames** [comment]
@lsmith77 when it's ready. :wink: See the README for this project for details on how to build and test.

**Comment by lsmith77** [comment]
ok thx. one question, does is new “mail” still based on Evolution? because I have some issues with Evolution (temporarily) loosing connections to google for hours or even days .. it fixes itself after a while or when I re-authenticate.

**Comment by tintou** [comment]
It is, but the issue you have with evolution is because there are too many users of Evolution as the Google Auth key is shared with all the distributions…
We will use our own key to connect to Google Accounts

**Comment by lsmith77** [comment]
great!

is there an outline somewhere of the goals and state of this new development?

I am especially interested in plans in regards to saved searches.

**Comment by danrabbit** [comment]
@lsmith77 we're tracking the progress of the rewrite in this project: https://github.com/elementary/mail/projects/2

Right now we're primarily looking to reach feature parity with the Geary-based mail. There is not a focus on implementing new features currently.
