### ISSUE TITLE
I cannot sign into any accounts.

### ISSUE THREAD

**Issue by YumeDragoon** [elementary/mail#485]
I literally cannot sign into anything. No matter what  I try or do! Google gave me a critical security risk as soon as the sign in failed. Please Fix this!!!

**Comment by ericpritchett** [comment]
This is something Google has done, but I agree that the error message within Mail could be better. If I understand the issue correctly, as I've had the same issue, Mail states "Unable to validate: Username or password incorrect". Google then states the following (via email and weblink):

"Less secure app blocked
Google blocked the app you were trying to use because it doesn't meet our security standards.
Some apps and devices use less secure sign-in technology, which makes your account more vulnerable. You can turn off access for these apps, which we recommend, or turn on access if you want to use them despite the risks. Google will automatically turn this setting OFF if it's not being used."

You have two options to get around this:

1. Turn on 2-step verification (https://support.google.com/accounts/answer/185839), so you can generate an app password for Mail (https://support.google.com/accounts/answer/185833?hl=en). You need to turn on 2-step verification to generate an app password.

or

2. https://myaccount.google.com/security > Less secure app access > Turn on access (not recommended)

Option 1 is the better choice, but option 2 is available as well. I hope that helps.

**Comment by andirsun** [comment]
> This is something Google has done, but I agree that the error message within Mail could be better. If I understand the issue correctly, as I've had the same issue, Mail states "Unable to validate: Username or password incorrect". Google then states the following (via email and weblink):
> 
> "Less secure app blocked
> Google blocked the app you were trying to use because it doesn't meet our security standards.
> Some apps and devices use less secure sign-in technology, which makes your account more vulnerable. You can turn off access for these apps, which we recommend, or turn on access if you want to use them despite the risks. Google will automatically turn this setting OFF if it's not being used."
> 
> You have two options to get around this:
> 
> 1. Turn on 2-step verification (https://support.google.com/accounts/answer/185839), so you can generate an app password for Mail (https://support.google.com/accounts/answer/185833?hl=en). You need to turn on 2-step verification to generate an app password.
> 
> or
> 
> 1. https://myaccount.google.com/security > Less secure app access > Turn on access (not recommended)
> 
> Option 1 is the better choice, but option 2 is available as well. I hope that helps.

You save my life with the first advice. Thanks a lott

**Comment by marbetschar** [comment]
Closing because this probably has been solved in the mean time.
