### ISSUE TITLE
Mail support for Modern Microsoft Authentication 

### ISSUE THREAD

**Issue by im-barney** [elementary/mail#488]
Mail has no way to get mail from a Microsoft Office365 mail account without using IMAP.
Many organisations are removing support for this aging protocol due to security concerns. IMAP doesn't (to my knowledge) work with any kind of multi-factor authentication which is also becoming more prevalent and important.

Building support for Microsoft's Modern Authentication in to Mail will allow it to be used with secure corporate mail systems.

**Comment by janxkoci** [comment]
> IMAP doesn't (to my knowledge) work with any kind of multi-factor authentication which is also becoming more prevalent and important.

I'm not sure if this is what you meant, but I'm using Gmail with 2FA and a per-app password for Mail.

Anyway, I think the plan is to handle this in [Online accounts](https://github.com/elementary/switchboard-plug-onlineaccounts).

**Comment by im-barney** [comment]
I think my post was slightly ambiguous - I meant that MFA is becoming more prevalent, not IMAP.
IMAP is going in the other direction :-)
I haven't found any way to access a corporate Office 365 mail account which doesn't support IMAP.
If Online Accounts can authenticate to an Office 365 account then auth directly from Mail is moot.

**Comment by janxkoci** [comment]
I see. I mostly use gmail and university email, no MS365, so I dunno, but AFAIK Evolution is able to handle that and in the [recent elementary blog post](https://blog.elementary.io/updates-for-july-2020/) they write about switching to Evolution backend.

> If Online Accounts can authenticate to an Office 365 account then auth directly from Mail is moot.

It cannot now, but I understand this will be the future interface for setting up email (and other) accounts.

**Comment by marbetschar** [comment]
@janxkoci is right, this issue is better suited in Online Accounts and a duplicate of https://github.com/elementary/switchboard-plug-onlineaccounts/issues/42.

For context: elementary Mail does indeed switch to the Evolution backend - therefore it's code is undergoing a major rework and integration with Online Accounts should get much better. However, I'm not quite sure if Microsoft Authentication will be included from the get go - but it is certainly the plan to support modern authentication protocols in Online Accounts at some point.
