### ISSUE TITLE
[Gmail] Fails to access drafts folder

### ISSUE THREAD

**Issue by kdwk** [elementary/mail#620]
## What Happened

https://user-images.githubusercontent.com/39268094/126264645-aa63c05e-eaae-458f-a522-0355216319b0.mp4

Drafts cannot be saved to the Drafts folder with Gmail.

## Expected Behavior

Drafts are saved correctly to the Gmail 'Drafts' folder

## Steps to Reproduce

1. Sign in to a Gmail account
2. Attempt to save a draft

## Platform Information

![Screenshot from 2021-07-14 10-55-34](https://user-images.githubusercontent.com/39268094/126264717-e3b464df-0c14-4a95-bcba-8a27fd13795d.png)
Mail 6.0.0

**Comment by marbetschar** [comment]
Does it work if you do the following?

1. Make sure elementary Mail is closed
2. Install Evolution (`sudo apt install evolution`)
3. Start Evolution and wait a few seconds (your mail account should already be correctly configured in Evolution)
4. Close Evolution
5. Start elementary Mail
6. Try again to save a draft

Explanation: I assume Evolution does something more to recognize well known folders at startup at the very first time a new account is configured (which we are probably missing in elementary Mail right now). Once Evolution did whatever it does, it seems the changes are propagated to elementary Mail.

**Comment by danrabbit** [comment]
Gmail actually has some weird folder paths for several folders. I'm not sure if it's possible to look up what folders are on the server and try to do some guessing/matching. But this is the config I have:

Drafts: `folder://[Gmail]/Drafts`
Sent: `folder://[Gmail]/Sent Mail`
Archive: `folder://[Gmail]/All Mail`
Trash: `folder://[Gmail]/Trash`
Junk: `folder://[Gmail]/Spam`

**Comment by marbetschar** [comment]
@danrabbit yeah; we should probably add a Google Online Account dialog anyways since EDS allows adding a Google collection account which would then (idealy) pre-configure Mail, Calendar and Tasks in one go.

While tinkering through the code, I found the following which shows how Evolution initializes a Google backend using EDS:
https://gitlab.gnome.org/GNOME/evolution/-/blob/master/src/modules/mail-config/e-mail-config-google-summary.c
