### ISSUE TITLE
Email aliases

### ISSUE THREAD

**Issue by ghost** [elementary/mail#636]
## Problem
Since new Mail app uses now new online accounts settings, there is no other way to manage email accounts. Previously when email was added, one could go to account settings and add email aliases.

## Proposal
Expand online accounts to enable that feature or restore previous settings to include alias settings

**Comment by cassidyjames** [comment]
This would be great as I know we use aliases for the elementary email accounts and I use it for my personal Fastmail account as well.

**Comment by wout** [comment]
@caasi-dev If you install Evolution, you can create aliases in there and they'll show up in Mail as well. I know it's a workaround, but if it's a pressing issue, that's a temporary solution.

**Comment by nevillepark** [comment]
> @caasi-dev If you install Evolution, you can create aliases in there and they'll show up in Mail as well. I know it's a workaround, but if it's a pressing issue, that's a temporary solution.

I had successfully been doing this, but in the latest version of Mail, it doesn't seem to be working; there are no other email address options when composing a message. Has that feature been removed?

**Comment by marbetschar** [comment]
It has not been removed on purpose, but maybe its a side effect of this fix:

https://github.com/elementary/mail/pull/769

**Comment by Soljanka** [comment]
Is there any other workaround to use Mail 6.4 with email aliases?

**Comment by wout** [comment]
Are there plans to re-implement email aliases? For me personally, it's one of the few missing features that are holding me back from using Mail as my default email client.

I love the work done so far. It's so much better already!

**Comment by leolost2605** [comment]
@wout first of all thanks for your positive feedback, glad you like the updates to mail! :)

> If you install Evolution, you can create aliases in there and they'll show up in Mail as well. I know it's a workaround, but if it's a pressing issue, that's a temporary solution.

This workaround should still work although I think only if you install evolution using `sudo apt install evolution` and not via flatpak.

I'd be happy to implement alias configuration but I'm not 100% sure where:
1. The Online Account settings might be a good place as there is also the normal address configured and you probably don't want to change an alias later on
2. The mail app on the other hand would be good because then you have the configuration you might want to be doing later in one place (like with the signatures). Also given the uncertainty of a future flatpak portal, using the online accounts for configuring might only duplicate work we will have to do later.

Any preferences here? :)
Also maybe @danirabbit has some suggestions?

**Comment by wout** [comment]
> This workaround should still work although I think only if you install evolution using sudo apt install evolution and not via flatpak/appcenter.

Ah, that was the issue. I installed it via Flathub. Thanks!

> Any preferences here? :)

I think the best place would be in the app itself, similar to Signatures. Personally, I don't like it when I have to switch to a completely different context to change preferences. I get that it's useful in relation to setting up accounts, but email aliases are something else. Anyway, that's my opinion. :)

**Comment by wout** [comment]
There's one thing I'd like to add here. If someone sends an email to one of the aliases, and you reply to it, the reply should have the correct alias selected in the From field. Currently, that's not the case. Let me know if I need to open a separate issue for it.

**Comment by leolost2605** [comment]
> There's one thing I'd like to add here. If someone sends an email to one of the aliases, and you reply to it, the reply should have the correct alias selected in the From field. Currently, that's not the case.

#956 should fix this

**Comment by wout** [comment]
That's great! Thanks!
