### ISSUE TITLE
Missing documentation for EDS

### ISSUE THREAD

**Issue by Letterus** [elementary/mail#695]
## What Happened
It seems main elementary OS PIM/productivity apps rely on [Evolution Data Server (EDS)](https://gitlab.gnome.org/GNOME/evolution-data-server) as a backend.

As a consequence EDS becomes an important/main software component of elementary OS. Only recently GNOME seems to have removed any EDS documentation that was placed at https://developer.gnome.org/eds/. This of course is a GNOME issue at first hand, but question arises if there should be documentation available that resides at sites of elementary OS for EDS and its client libs, mainly for reasons of convience and accessibility.

This affects reports as https://github.com/elementary/switchboard-plug-onlineaccounts/issues/228 as well of course, because having documentation available quickly would make it more easy to check general implementation approaches. And to develop new software relying on EDS of course.

**Comment by tintou** [comment]
Everything has been moved to https://developer-old.gnome.org/eds/

We also have a good coverage of the symbols in https://valadoc.org/

**Comment by Letterus** [comment]
> Everything has been moved to https://developer-old.gnome.org/eds/
> 
> We also have a good coverage of the symbols in https://valadoc.org/

@tintou Thank you, great to know! Is there a good place to link the API relevant for app development?

**Comment by tintou** [comment]
I don't think that we have a central place for this, but it is always assumed that the API documentation is in https://valadoc.org/

**Comment by Letterus** [comment]
Ok, thank you, then nevermind. The stuff other I need to report to the GNOME project.

**Comment by Letterus** [comment]
I tend to reopen this issue. API doc is there. But to me it seems very hard to get how to use it correctly.

Others seem to have experienced that issue as well: https://github.com/aggalex/Contacts/issues/25

**Comment by marbetschar** [comment]
@Letterus I agree documentation could be better. But resources are scarce and some one has to write such documentation and (the harder part) keep it relevant. This is a huge task, especially because we are dealing with lots of different libraries.

But I get your point; I found it quite hard to get started too - but eventually found my way around and what really helped was interacting with the community. So basically just keep asking questions and try to put the knowledge to use and the fog eventually disappears. IMHO https://valadoc.org/ does quite a good job, once it "clicked".

Also, we can always add further documentation to https://docs.elementary.io/develop if its of broader use.

**Comment by Letterus** [comment]
@marbetschar Thanks. Yes, I'm digging into this, see https://github.com/elementary/switchboard-plug-onlineaccounts/issues/200.
But eventually once I understood how things work I'd try to write a very little, very short introduction to EDS - just to make it easier to get started and to provide some basic means of how it works and how those API are meant.
